# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

brewery_list = [
    [ "Brasserie Les 2&nbsp;Frères", "Brasserie Les 2 Frères se distingue quant à l'unicité de ses produits, des bières de dégustation à partager avec vos proches. La brasserie est principalement connue pour ses Charles-Henri blanche et ambrée ainsi que sa Hickson&nbsp;IPA.", 1 ],
    [ "Microbrasserie Alchimiste", "La Microbrasserie Alchimiste poursuit sa mission de faire des bières de qualité supérieure, 100% naturelles, que vous saurez apprécier pour leur douceur et leur équilibre. En plus de fabriquer La Claire, l'Écossaise, l'India Pale Ale, la Blanche, la Bock de Joliette, la Légitime et la Rousse douce, l'Alchimiste propose des bières de spécialités: l'Eisbock et la Stout Impériale. Tant les néophytes que les grands amateurs seront&nbsp;comblés.", 2 ],
    [ "Microbrasserie Archibald", "La microbrasserie Archibald utilise des procédés de fabrication qui s’inspirent des traditions ancestrales allemandes. Elle brasse également des bières de type belge auxquelles elle ajoute des épices, des écorces d'orange et des céréales crues. La microbrasserie propose 11 variétés de bière en plus de nombreuses bières&nbsp;saisonnières.", 3 ],
    [ "Microbrasserie La&nbsp;Barberie", "Plus de 200 recettes de bière ont déjà été imaginées, brassées, dégustées et partagées à La Barberie. À travers les différents courants qui ont marqué l’industrie, que ce soit dans le brassage d’innovation ou de tradition, La Barberie continue de se démarquer en brassant des bières d’exception de qualité&nbsp;supérieure.", 4 ],
    [ "BEAU'S", "Depuis 2006, Beau’s All Natural brasse des bières intéressantes et savoureuses comme la Lug Tread Lagered Ale en n’utilisant que les meilleurs ingrédients et de l’eau de source locale. Son équipe est fière d’élaborer une bière artisanale unique, délicieuse et certifiée biologique. Il s'agit d'une brasserie primée, familiale, amicale et artisanale à&nbsp;100&nbsp;%.", 5 ],
    [ "Microbrasserie Bellechasse", "La Microbrasserie de Bellechasse brasse des bières de long vieillissement au pied du Parc du Massif du Sud, dans le village de Buckland. Elle produit des bières de soif et de dégustation avec une eau qui naît des montagnes. C'est pourquoi l'on affirme que la bière de Bellechasse coule de&nbsp;source!", 6 ],
    [ "La Microbrasserie<br/>Le&nbsp;Bilboquet", "Le Bilboquet se spécialise dans les produits brassicoles de dégustation, comme les bières non filtrées, refermentées en baril et en bouteille, qu'elle a lentement laissé vieillir. Elle propose une sélection de 15 bières faites à partir d'orge malté, de blé et de houblon de première qualité et de levures&nbsp;sélectionnées.", 7 ],
    [ "Microbrasserie Le&nbsp;BockAle", "Le BockAle est une microbrasserie industrielle qui se spécialise dans la conception, le brassage et la vente de bières artisanales. Elle vous propose des bières régulières et saisonnières vous permettant de faire la découverte de nouvelles sensations&nbsp;gustatives&nbsp;!", 8 ],
    [ "Microbrasserie Le&nbsp;Castor", "La mission de cette microbrasserie est de préparer des bières super savoureuses à l'aide d’ingrédients biologiques des plus fins. Ses proprios se consacrent sans arrêt au développement de leur sélection de bières. Donc, si au bout de quelques mois, vous ne voyez aucunes nouveauté, informez-vous!", 9 ],
    [ "Microbrasserie Charlevoix", "Depuis maintenant 1998, les brasseurs charlevoisiens ne cessent de laisser libre cours à leur imagination afin de satisfaire les amateurs de bières spéciales les plus exigeants. C'est au cœur de Baie-Saint-Paul que sont brassées les bières d'inspiration belge 'Dominus Vobiscum' Blanche, Ambrée, Double et Triple, ainsi que les bières 'Vache Folle' ESB et Milk&nbsp;Stout.", 10 ],
    [ "Brasserie La&nbsp;Chouape", "Guidés par leur passion pour la bière et inspirés par les traditions paysannes familiales, les fondateurs de la Brasserie La Chouape brassent des bières savoureuses, originales et des plus naturelles. La brasserie propose quatre familles de bière refermentées en bouteille pour un pétillant 100%&nbsp;naturel.", 11 ],
    [ "La Microbrasserie Corsaire", "La microbrasserie Corsaire se démarque principalement grâce à son style unique et inimitable et son offre de bières de type britannique. Découvrez ses fabuleux produits réguliers, saisonniers ainsi que ses bières offertes en édition&nbsp;spéciale.", 12 ],
    [ "Creemore Spring", "Pour une petite brasserie de village, la Creemore Spring a une sélection assez impressionnante de bières, toutes inspirées de grandes traditions européennes. Que vous soyez du genre bière forte, douce, amère ou rafraîchissante, nous avons ce qu’il faut pour étancher votre soif.", 13 ],
    [ "Brasserie Dieu&nbsp;du&nbsp;ciel!", "La microbrasserie Dieu du ciel! propose une variété impressionnante de bières régulières faisant partie de leur répertoire classique. Elle offre également la série Momentum proposant 12 bières différentes qui encouragent l'exploration et la découverte brassicoles&nbsp;! A chaque mois sa&nbsp;bière.", 14 ],
    [ "Brasserie Dunham", "Le porte-folio de Brasserie Dunham se veut le reflet de la passion de ses artisans pour ce noble nectar du peuple. Inspirés par les traditions brassicoles classiques européennes, leur savoir-faire est résolument tourné vers l'exploration et le renouveau des genres. Que ce soit vieillie en barrique, chargée en lupuline, intensément fruitée ou délicatement sauvage, assez de bavardage …Trinquez!", 15 ],
    [ "Farnham Ale & Lager", "Farnham Ale & Lager s'est donné comme mission de rendre la bière artisanale accessible à tous. Avec ses produits réguliers et saisonniers, la brasserie montérégienne couvre la majorité des styles de bière recherchés par les&nbsp;amateurs.", 16 ],
    [ "Frampton Brasse", "Frampton Brasse est née des intérêts communs des membres d'une même famille. Rien de tel qu’un retour aux sources à la découverte de 8 bières authentiques et brassées en&nbsp;Beauce!", 17 ],
    [ "La Brasserie&nbsp;Générale", "L'équipe de la Brasserie Générale brasse une vaste gamme de bières 'régulières' pour le plaisir des amateurs. Laissez-vous séduire par l'une des 18 bières qu'elle&nbsp;vous&nbsp;propose.", 18 ],
    [ "Microbrasserie Glutenberg", "L'ambition première des fondateurs était de brasser les meilleures bières sans gluten qui soient. Emportés par l'enthousiasme, ils ont créé des bières qui comptent parmi les meilleures au monde. Couronnées à plusieurs reprises, leurs bières valent le&nbsp;détour!", 19 ],
    [ "Goose Island", "C'est un plaisir de voir de nouveaux produits Goose Island faire leur entrée au Québec, dont la Goose IPA. Elle présente une belle amertume, un arôme floral et des notes d’agrumes et d’abricot. Cette bière a remporté six médailles pendant dix-sept années consécutives au Great American Beer Festival. Pour une bière développée en 1990, il faut dire que les brasseurs de l’époque ont fait preuve&nbsp;d’audace.", 20 ],
    [ "Grandville Island", "C'est en 1984 qu'a été fondée la toute première microbrasserie au Canada: Granville Island Brewing. Motivés par le désir de brasser une bière haut de gamme naturelle et remplie de saveur, les brasseurs ont présenté au public de la région leur première création, la Island Lager. Au fil du temps, ils ont ajouté à leur gamme d'autres bières uniques et inspirées de la Côte&nbsp;Ouest.", 21 ],
    [ "Microbrasserie Le&nbsp;Grimoire", "Au fil du temps, la microbrasserie Le Grimoire a commercialisé plusieurs bières fruitées ainsi que d’autres plus fortes pour plaire à tous les genres. Cette microbrasserie est grandement appréciée par sa nombreuse clientèle qui provient de partout au Québec. Vous vous devez de découvrir ses bières savoureuses et&nbsp;uniques.", 22 ],
    [ "Microbrasserie HopEra", "La microbrasserie propose 3 gammes de produits : 6 produits réguliers reprenant les principaux styles de bière connus, complétés par des produits périodiques selon les saisons ainsi que des produits éclectiques visant ainsi tout style de consommateur. Quelle sera la&nbsp;vôtre!", 23 ],
    [ "Brasseurs Illimités", "Brasseurs Illimités crée des bières de dégustation inspirées des grands chefs-d'œuvre issus des traditions brassicoles. Brasseurs illimités vous suggère un large éventail de créations conçues à partir de riches saveurs extraites des meilleurs&nbsp;malts.", 24 ],
    [ "Microbrasserie du Lac&nbsp;St&#8209;Jean", "Puiser le meilleur de ce qui existe dans la tradition brassicole et l’enraciner dans la réalité d’ici, voici la raison d'être de Microbrasserie du lac St-jean. Avec plus d'une dizaine de bières des plus renversantes, vous saurez combler votre&nbsp;soif!", 25 ],
    [ "La Microbrasserie Le Lion&nbsp;d'Or", "La Microbrasserie Le Lion d'Or de Lennoxville vous propose des bières brassées à la main en petits lots, utilisant seulement les meilleurs ingrédients naturels. Dégustez l'une de ses 6 variétés pour le plus grand bonheur de vos&nbsp;papilles.", 26 ],
    [ "Brasserie McAuslan (St&#8209;Ambroise)", "Les bières de la Brasserie McAuslan sont un incontournable. Découvrez l'impressionnante variété de bières St-Ambroise, McAuslan ou Griffon et dégustez des bières spécialisées de renommée mondiale élaborées à la perfection!", 27 ],
    [ "Brasseurs du Monde", "Brasseurs du Monde propose tant des bières de soif, développées pour le grand public, que des bières fortes et généreuses, appréciées par un nombre grandissant de consommateurs. Brasseurs du Monde propose un grand choix de bières répondant aux attentes des&nbsp;consommateurs.", 28 ],
    [ "Mons", "La brasserie Belgh Brasse est la Brasserie canadienne de l'année, élue meilleure bière au monde pour une 2e année consécutive. Ses bières sont brassées avec de l'eau de l'Esker d'Abitibi. Vous vous devez d'y&nbsp;goûter&nbsp;!", 29 ],
    [ "Moosehead", "La brasserie Moosehead Breweries Limited, située à St-Jean, Nouveau-Brunswick, est la plus vieille brasserie indépendante au Canada. Elle fût fondée en 1867 et est toujours dirigée par la famille, maintenant la sixième génération. La marque a déjà reçu un grand nombre de récompenses internationales pour la qualité de ses produits. Moosehead produit aussi, sous contrat, plusieurs bières&nbsp;internationales.", 30 ],
    [ "Microbrasserie Le&nbsp;Naufrageur", "Dans la Baie-des-Chaleurs, les bières de la microbrasserie Le Naufrageur ont la cote. Maintenant, de fins connaisseurs du Québec et de six États de la Nouvelle-Angleterre leur accordent officiellement leurs lettres de noblesse. Ne passez pas à&nbsp;côté!", 31 ],
    [ "Les Brasseurs du Nord (Boréale)", "Les Brasseurs du Nord priorise les ingrédients naturels et valorise les méthodes écoresponsables. Chaque Boréale offre une combinaison unique de goûts et de saveurs. Bières classiques, bières de collection, bières saisonnières ou brassins spéciaux, à chacun sa&nbsp;bière!", 32 ],
    [ "Les bières de la Nouvelle&#8209;France", "Les bières de la Nouvelle-France, c'est huit variétés de bières dont 4 sans gluten. Malgré un important volume de fabrication, la microbrasserie est toujours demeurée une entreprise familiale à échelle humaine et c’est ce qui frappe quand on rencontre la famille Lessard qui en est propriétaire. Une grande expertise qui garantit un goût et une stabilité à la&nbsp;bière.", 33 ],
    [ "Microbrasserie Pit&nbsp;Caribou", "La Microbrasserie Pit Caribou s’est donnée comme mission, depuis son démarrage le 23 juin 2007, d’offrir des bières gaspésiennes de qualité en misant sur les ressources locales. La microbrasserie a reçu plusieurs distinctions au cours des dernières années. La Microbrasserie Pit caribou, des bières qui valent le&nbsp;détour!", 34 ],
    [ "Brasseurs RJ", "Brasseurs RJ doit sa réussite à la qualité de ses produits sans passer sous silence le vent de changement qu'elle insuffle dans le paysage brassicole québécois. Les membres de l'équipe ont fait preuve d'audace avec la mise en marché de la première blanche de type belge au Québec, la Cheval Blanc et l'introduction du premier emballage mixte de produits le Trio des Connaisseurs Belle&nbsp;Gueule.", 35 ],
    [ "Microbrasserie du Saguenay (La&nbsp;Voie&nbsp;Maltée)", "Adeptes de La Voie Maltée, vous serez comblés. Les bières VM sont maintenant disponibles en canettes. Cette microbrasserie se distingue par son savoir-faire et par sa série très intéressante de 11 bières artisanales. Elle est également une pionnière dans le volet de la cuisine à la&nbsp;bière.", 36 ],
    [ "Les Brasseurs du temps (BDT)", "Les Brasseurs du Temps produisent leur bière sur place à partir d'ingrédients de qualité supérieure. Envie de sortir des sentiers battus? Profitez d'une diversité de bières impressionnante qui saura combler autant le grand public que les amateurs&nbsp;aventuriers.", 37 ],
    [ "Microbrasserie La Tour à&nbsp;bière", "La Tour à bière a pour mission de faire découvrir des bières réalisées à la manière saguenéenne en offrant de nouvelles saveurs et en utilisant des malts québécois, canadiens et mondiaux. La Microbrasserie a mis sur le marché 8 sortes de bière pour lesquelles l'embouteillage est, encore aujourd'hui, réalisé à la&nbsp;main.", 38 ],
    [ "La Trappe", "La bière trappiste de La Trappe est brassée depuis 1884 par la brasserie de Koningshoeven. Les bières La Trappe sont toutes des bières pures. Avec patience, amour, passion et un artisanat traditionnel, ces bières uniques sont le résultat d'un brassage selon les recettes secrètes des&nbsp;Trappistes.", 39 ],
    [ "Microbrasserie Le Trou du&nbsp;Diable", "Directement de leur nouvelle brasserie, amoureusement appelée «La Shop», la microbrasserie Le Trou du Diable embouteille plus d’une quinzaine de variétés tout au long de l’année qui sauront à la fois plaire au néophyte et satisfaire&nbsp;l’initié.", 40 ]
]

brewery_list.each do |name, description, order|
  Brewery.create( name: name, description: description, order: order )
end